/*            *
 * DOBRODOSLI NAM NA...       *
 * ------------- Nova Era RolePlay!
 *       *       =====================
 *____________________________________*
 *                             *
 * Verzija: 2.4    *
 *                             *
 * Developer: DentisT_and_Brace
 *               *
 * Zadnji update: 22.01.2021      *
 *
 * Mapper: Mata | Vlasnik: Makso          *
 *                   *
 */

#if INCLUDE_NERP_MODULES == 0
	#endinput
#endif

//////////////VERZIJA/////////////////

#define NERP_VERSION_MAJOR "3"
#define NERP_VERSION_MINOR "1"
#define NERP_VERSION_PATCH "2"
#define NERP_VERSION_RELEASE "1"

#define NERP_VERZIJA "v"NERP_VERSION_MAJOR"."NERP_VERSION_MINOR"."NERP_VERSION_PATCH"-R"NERP_VERSION_RELEASE""

//////////////////KONSTANTE///////////

#define NERP_TEXT_NEXT "Dalje"
#define NERP_TEXT_BACK "Nazad"
#define NERP_TEXT_EXIT "Izlaz"

/////////////VARIJABLE///////////////
////////////////SPRITES/////////////

#define NERP_KRUG "ld_beat:chit"

//////////////////////////////////
#define banka_ulaz_x 1459.4175
#define banka_ulaz_y -1010.7699
#define banka_ulaz_z 26.8438

#define banka_izlaz_x
#define banka_izlaz_y
#define banka_izlaz_z

//sef

#define banka_ulaz_x_sef
#define banka_ulaz_y_sef
#define banka_ulaz_z_sef

#define banka_izlaz_x_sef 1470.5063
#define banka_izlaz_y_sef -986.2422
#define banka_izlaz_z_sef 2051.6162

// == Pekara == //
#define pekara_x 802.6494
#define pekara_y -1629.6715
#define pekara_z 13.3828

#define pekara_ulaz_x 811.1299
#define pekara_ulaz_y -1616.0647
#define pekara_ulaz_z 13.5469

#define pekara_mlin_x 1073.2822
#define pekara_mlin_y -345.3524
#define pekara_mlin_z 73.9922

#define pekara_dostava_x 789.9418
#define pekara_dostava_y -1614.7734
#define pekara_dostava_z 13.3828